# Generated by Django 3.0.5 on 2020-04-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0002_auto_20200415_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_ref',
            field=models.SlugField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
